# Generated by Django 5.0.4 on 2024-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_published',
        ),
        migrations.AddField(
            model_name='movie',
            name='year_published',
            field=models.IntegerField(default=2000),
        ),
    ]
